networks:
  sotehus:
    external: true
services:
  influxdb2:
    image: influxdb:2
    restart: always
    ports:
      - 8087:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: sotehus
      DOCKER_INFLUXDB_INIT_BUCKET: sotehus_bucket
      DOCKER_INFLUXDB_INIT_RETENTION: 300d
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: bind
        source: /var/lib/sotehus/influxdb2-data
        target: /var/lib/influxdb2
      - type: bind
        source: /etc/influxdb2-config
        target: /etc/influxdb2
    networks:
      - sotehus
    container_name: influxdb2
secrets:
  influxdb2-admin-username:
    file: credentials/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: credentials/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: credentials/.env.influxdb2-admin-token
